openapi: '3.0.0'
info:
  version: 1.0.0
  title: Slack Web API docs
  description: Slack Web TEAM A의 API 문서입니다
  license:
    name: MIT
host: http://localhost:3000
basePath: /
paths:
  $ref: './paths/_index.yaml'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Thread:
      type: object
      required:
        - id
        - createdAt
        - updatedAt
      properties:
        id:
          type: integer
        userId:
          type: integer
        channelId:
          type: integer
        createdAt:
          type: string
        updatedAt:
          type: string
        deletedAt:
          type: string
    Message:
      type: object
      required:
        - id
        - content
        - isHead
        - createdAt
        - updatedAt
      properties:
        id:
          type: integer
        content:
          type: string
        isHead:
          type: string
        userId:
          type: integer
        threadId:
          type: integer
        createdAt:
          type: string
        updatedAt:
          type: string
        deletedAt:
          type: string
    User:
      type: object
      required:
        - _id
        - name
      properties:
        _id:
          type: number
          description: id
        name:
          type: string
          description: 유저 이름
    Error:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
  responses:
    BadRequest:
      description: 잘못된 요청
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            success: false
            message: 잘못된 요청
    InternalServerError:
      description: 서버 에러
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            success: false
            message: 서버 내부 오류
    DBError:
      description: 데이터베이스 에러
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            success: false
            message: 데이터베이스 에러
